PDFViewer/Models/ErrorViewModel.cs
using System;

namespace PDFViewer.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PDFViewer/Models/FileContentDTO.cs
namespace PDFViewer.Models
{
    public class FileContentDTO
    {
        public string FileContent { get; set; }
    }
}

PDFViewer/Models/SvgAccessModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PDFViewer.Models
{
    public class SvgAccessModel
    {
        [Key]
        public int Id { get; set; }

        [DisplayName("Print Svc URL")]
        [Required]
        public string PrintSvcUrl { get; set; }

        [DisplayName("Auth Svc URL")]
        [Required]
        public string AuthSvcUrl { get; set; }

        [DisplayName("Çevre Sistem")]
        [Required]
        public string CevreSistem { get; set; }

        [DisplayName("Şirket ID")]
        [Required]
        public int SirketID { get; set; }

        [DisplayName("User")]
        [Required]
        public string User { get; set; }

        [DisplayName("Password")]
        [Required]
        public string Password { get; set; }
    }
}

PDFViewer/Models/SvgModel.cs
namespace PDFViewer.Models
{
    public class SvgModel
    {
        public SvgAccessModel svgAccessModel { get; set; }
        public SvgPrintModel svgPrintModel { get; set; }
    }
}

PDFViewer/Models/SvgPrintModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PDFViewer.Models
{
    public class SvgPrintModel
    {
        [DisplayName("Document Type Code")]
        [Required]
        public string DocumentTypeCode { get; set; }

        [DisplayName("Policy No")]
        [Required]
        public int PolicyNo { get; set; }

        [DisplayName("Endorsement No")]
        [Required]
        public int EndorsementNo { get; set; }

        [DisplayName("Renewal No")]
        [Required]
        public int RenewalNo { get; set; }

        [DisplayName("Digital Approval")]
        [Required]
        public string DigitalApproval { get; set; }

        [DisplayName("Is Masked")]
        [Required]
        public string IsMasked { get; set; }
    }
}

PDFViewer/Models/TokenDTO.cs
namespace PDFViewer.Models
{
    public class TokenDTO
    {
        public string Token { get; set; }
    }
}

PDFViewer/Controllers/Base64Controller.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using PDFViewer.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Net.Http.Json;
using PDFViewer.Models;

namespace PDFViewer.Controllers
{
    public class Base64Controller : Controller
    {

        private readonly ApplicationDbContext db;
        private HttpClient _httpClient;

        private static string token; //access token for authentication
        private static string fileContent; //file content retrieved from print svc

        public Base64Controller(ApplicationDbContext db, HttpClient httpClient)
        {
            this.db = db;
            _httpClient = httpClient;
        }

        public IActionResult Index()
        {
            var objUserList = db.SvgAccessModels.ToList();
            ViewBag.msg = objUserList[0];

            if(fileContent != null)
            {
                ViewBag.content = fileContent;
                fileContent = null;
            }

            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> PrintPDF(Models.SvgPrintModel model)
        {
            if (ModelState.IsValid)
            {
                fileContent = await CreateDocument(model);
                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Access(Models.SvgAccessModel formModel)
        {
            if (ModelState.IsValid)
            {
                var currentConfig = db.SvgAccessModels.FirstOrDefault(x => x.Id == formModel.Id);
                if(currentConfig == null)
                {
                    return NotFound();
                }

                currentConfig.PrintSvcUrl = formModel.PrintSvcUrl;
                currentConfig.AuthSvcUrl = formModel.AuthSvcUrl;
                currentConfig.CevreSistem = formModel.CevreSistem;
                currentConfig.SirketID = formModel.SirketID;
                currentConfig.User = formModel.User;
                currentConfig.Password = formModel.Password;

                db.SaveChanges();

                return RedirectToAction("Index");
            }   

            return PartialView("_AccessKey",formModel);
        }

        private async Task<string> CreateAccessToken(Models.SvgAccessModel currentConfig)
        {
            _httpClient.BaseAddress = new Uri("https://localhost:7079");

            _httpClient.DefaultRequestHeaders.Accept.Clear();
            _httpClient.DefaultRequestHeaders.Add("SOURCE", "EXIP-TEB");
            _httpClient.DefaultRequestHeaders.Add("Transaction-Id", Guid.NewGuid().ToString());

            var requestContent = ConstructCreateAccessTokenJson(currentConfig);
            var buffer = System.Text.Encoding.UTF8.GetBytes(requestContent);
            var byteContent = new ByteArrayContent(buffer);
            byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");

            var response = await _httpClient.PostAsync("api/InipAuth/CreateToken", byteContent);
            response.EnsureSuccessStatusCode();
            if (response.IsSuccessStatusCode)
            {
                var resp = await response.Content.ReadFromJsonAsync<TokenDTO>();
                token = resp.Token;
            }

            return token;
        }

        private string ConstructCreateAccessTokenJson(Models.SvgAccessModel currentConfig)
        {
            var payload = new
            {
                username = currentConfig.User,
                password = currentConfig.Password,
                environment = currentConfig.CevreSistem,
                companyId = currentConfig.SirketID
            };

            string json = JsonSerializer.Serialize(payload);
            return json;
           
        }

        private async Task<string> CreateDocument(Models.SvgPrintModel printModel)
        {
            var fileContent = "";

            var objUserList = db.SvgAccessModels.ToList();
            var returnedToken = await CreateAccessToken(objUserList[0]);

            //_httpClient.BaseAddress = new Uri("https://localhost:7079");

            _httpClient.DefaultRequestHeaders.Clear();
            _httpClient.DefaultRequestHeaders.Add("Source", "ONLSVC-PRINT");
            _httpClient.DefaultRequestHeaders.Add("Transaction-Id", Guid.NewGuid().ToString());
            _httpClient.DefaultRequestHeaders.Add("Life4U-Auth-Token", returnedToken);

            var requestContent = ConstructCreateDocumentJson(printModel);
            var buffer = System.Text.Encoding.UTF8.GetBytes(requestContent);
            var byteContent = new ByteArrayContent(buffer);
            byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");

            var response = await _httpClient.PostAsync("api/InipPrinting/CreateDocument", byteContent);
            response.EnsureSuccessStatusCode();
            if (response.IsSuccessStatusCode)
            {
                var resp = await response.Content.ReadFromJsonAsync<FileContentDTO>();
                fileContent = resp.FileContent;
            }

            return fileContent;
        }


        private string ConstructCreateDocumentJson(Models.SvgPrintModel printModel)
        {
            var payload = new
            {
                documentCode = printModel.DocumentTypeCode,
                parameters = new[]
               {
                   new {name = "ILKPOLICENO", value=printModel.PolicyNo.ToString() },
                   new {name = "YENILEMENO", value=printModel.RenewalNo.ToString() },
                   new {name = "ZEYLNO", value=printModel.EndorsementNo.ToString() },
                   new {name = "dijitalOnay", value=printModel.DigitalApproval },
                   new {name = "MASKELIMI", value=printModel.IsMasked }

               }
            };

            string json = JsonSerializer.Serialize(payload);
            return json;

        }
    }
}

PDFViewer/Views/Base64/Index.cshtml
@model SvgPrintModel

<div class="main-container">
    <div class="base64">
        <h2>Convert Base64</h2>

        <div class="controller1">
            <div class="form-floating">
                <input type="file" id="file-selector" accept=".txt">
            </div>
        
            <button type="button" class="btn btn-primary" id="convertBtn" onclick="convertBase64()"><i class="bi bi-arrow-clockwise"></i> Convert to PDF</button>
        </div>

        <div id="alerts"></div>
   
    </div>
    <div class="svg">
        <h2>Call Printing Service</h2>
        <button type="button" class="btn btn-primary" style="float:right" data-bs-toggle="modal" data-bs-target="#accessKeyModal"><i class="bi bi-gear-fill">  </i>Settings</button>
        
        <partial name="_AccessKey" ></partial>

        <div class="print-svg-pdf" style="margin-top:3rem">
            <form method="post" asp-action="PrintPDF">
                <div class="mb-3">
                <label asp-for="DocumentTypeCode"></label>
                <input asp-for="DocumentTypeCode" class="form-control"/>
                 <span asp-validation-for="DocumentTypeCode" class="text-danger"></span>
                </div>
                <div class="mb-3">
                <label asp-for="PolicyNo"></label>
                <input asp-for="PolicyNo" class="form-control"/>
                <span asp-validation-for="PolicyNo" class="text-danger"></span>
                </div>
                <div class="mb-3">
                <label asp-for="EndorsementNo"></label>
                <input asp-for="EndorsementNo" class="form-control"/>
                <span asp-validation-for="EndorsementNo" class="text-danger"></span>
                </div>
                 <div class="mb-3">
                <label asp-for="RenewalNo"></label>
                <input asp-for="RenewalNo" class="form-control"/>
                <span asp-validation-for="RenewalNo" class="text-danger"></span>
                </div>
                <div class="mb-3">
                <label asp-for="DigitalApproval"></label>
                 <fieldset class="form-group" id="DigitalApproval">
                      <div class="form-check">
                        <label class="form-check-label">
                          <input asp-for="DigitalApproval" type="radio" class="form-check-input"  name="DigitalApproval" value="yes" checked/>
                          Yes
                        </label>
                      </div>
                      <div class="form-check">
                        <label class="form-check-label">
                          <input asp-for="DigitalApproval" type="radio" class="form-check-input"  name="DigitalApproval" value="no"/>
                          No
                        </label>
                      </div>
         
                </fieldset>
               </div>
                 <div class="mb-3">
                <label asp-for="IsMasked"></label>
                 <fieldset class="form-group" id="isMasked">
                      <div class="form-check">
                        <label class="form-check-label">
                          <input asp-for="IsMasked" type="radio" class="form-check-input" name="isMasked"  value="yes" checked/>
                          True
                        </label>
                      </div>
                      <div class="form-check">
                        <label class="form-check-label">
                          <input asp-for="IsMasked" type="radio" class="form-check-input" name="isMasked"  value="no" />
                          False
                        </label>
                      </div>
                </fieldset>
               </div>  
               <button type="submit" class="btn btn-success" style="float:right"><i class="bi bi-file-earmark-pdf"></i> Print PDF</button>
            </form>
        </div>

    </div>
</div>

<hr style="border: solid grey">

<div class="pdfview">
    @if (ViewBag.content != null)
     {
         <object id="pdf-result" style="width:100%; height:500px" type="application/pdf" data="data:application/pdf;base64,@ViewBag.content"></object>
        
     }
</div>

@section scripts{
    <script type="text/javascript" src="~/js/base64.js" asp-append-version="true"></script>
    @{
                <partial name="_ValidationScriptsPartial"></partial>
    }

} 

PDFViewer/Views/Shared/Access.cshtml
@model SvgAccessModel


      <div class="modal" id="accessKeyModal">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Configurations</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true"></span>
                </button>
              </div>
              <form asp-action="Access" method="post">
                  <div class="modal-body">        
                      <div class="mb-3">
                        
                        <label asp-for="PrintSvcUrl"></label>
                        <input asp-for="PrintSvcUrl" class="form-control"/>
                        <span asp-validation-for="PrintSvcUrl" class="text-danger"></span>
                                          
                      </div>
                      <hr>
                      <div class="mb-3">
                        <label asp-for="AuthSvcUrl"></label>
                        <input asp-for="AuthSvcUrl" class="form-control"/>
                        <span asp-validation-for="AuthSvcUrl" class="text-danger"></span>
                      
                      </div>
                       <div class="mb-3">
                        <label asp-for="CevreSistem"></label>
                        <input asp-for="CevreSistem" class="form-control"/>
                        <span asp-validation-for="CevreSistem" class="text-danger"></span>
                     
                      </div>
                       <div class="mb-3">
                         <label asp-for="SirketID"></label>
                        <input asp-for="SirketID" class="form-control"/>
                        <span asp-validation-for="SirketID" class="text-danger"></span>
                     
                      </div>
                       <div class="mb-3">
                         <label asp-for="User"></label>
                        <input asp-for="User" class="form-control"/>
                        <span asp-validation-for="User" class="text-danger"></span>
                  
                      </div>
                       <div class="mb-3">
                         <label asp-for="Password"></label>
                        <input type="password" asp-for="Password" class="form-control"/>
                        <span asp-validation-for="Password" class="text-danger"></span>
             
                      </div>        
                  </div>
                  <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Save changes</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  </div>
              </form>
            </div>
          </div>
        </div>

PDFViewer/Views/Shared/_AccessKey.cshtml
@model SvgAccessModel

      <div class="modal" id="accessKeyModal">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Configurations</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true"></span>
                </button>
              </div>

                @{
                     var data = ViewBag.msg;
                }

              <form asp-action="Access" method="post">
                  <div class="modal-body">        
                      <div class="mb-3">
                        
                        <label asp-for="PrintSvcUrl"></label>
                        <input asp-for="PrintSvcUrl" class="form-control" value="@data.PrintSvcUrl"/>
                        <span asp-validation-for="PrintSvcUrl" class="text-danger"></span>
                                          
                      </div>
                      <hr>
                      <div class="mb-3">
                        <label asp-for="AuthSvcUrl"></label>
                        <input asp-for="AuthSvcUrl" class="form-control" value="@data.AuthSvcUrl"/>
                        <span asp-validation-for="AuthSvcUrl" class="text-danger"></span>
                      
                      </div>
                       <div class="mb-3">
                        <label asp-for="CevreSistem"></label>
                        <input asp-for="CevreSistem" class="form-control" value="@data.CevreSistem"/>
                        <span asp-validation-for="CevreSistem" class="text-danger"></span>
                     
                      </div>
                       <div class="mb-3">
                         <label asp-for="SirketID"></label>
                        <input asp-for="SirketID" class="form-control" value="@data.SirketID"/>
                        <span asp-validation-for="SirketID" class="text-danger"></span>
                     
                      </div>
                       <div class="mb-3">
                         <label asp-for="User"></label>
                        <input asp-for="User" class="form-control" value="@data.User"/>
                        <span asp-validation-for="User" class="text-danger"></span>
                  
                      </div>
                       <div class="mb-3">
                         <label asp-for="Password"></label>
                        <input type="password" asp-for="Password" class="form-control" value="@data.Password"/>
                        <span asp-validation-for="Password" class="text-danger"></span>
             
                      </div>        
                  </div>
                  <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Save changes</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  </div>
              </form>
            </div>
          </div>
        </div>

PDFViewer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PDFViewer</title>
    <link rel="stylesheet" href="~/css/bootswatchtheme.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="PDFViewer.styles.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <!--<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PDFViewer</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="base64" asp-action="Index">base64</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="SVG" asp-action="Svg">SVG</a>
                    </li>-->
        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>*@
        <!--</ul>
            </div>
        </div>
    </nav>-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand">PDF Viewer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
           @*             <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Base64" asp-action="Index">base64</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Svg" asp-action="Index">SVG</a>
                        </li>*@
                    </ul>
           
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2022 - PDFViewer
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>